// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfJA6iiyABA1ZssUw0antNCZLww6L8Up0',
    appId: '1:889932435607:web:e83ad40e81cb00ce5b59d2',
    messagingSenderId: '889932435607',
    projectId: 'fashion-store-fe2d1',
    authDomain: 'fashion-store-fe2d1.firebaseapp.com',
    storageBucket: 'fashion-store-fe2d1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlCY1jBOl1ZJVi4PwVpVoUIzJyMSlo3Pg',
    appId: '1:889932435607:android:366e8bbea7cc68165b59d2',
    messagingSenderId: '889932435607',
    projectId: 'fashion-store-fe2d1',
    storageBucket: 'fashion-store-fe2d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnHLKaP02MiHCU3fsVlcUlLOjudvlRjgw',
    appId: '1:889932435607:ios:19627609cf4d74925b59d2',
    messagingSenderId: '889932435607',
    projectId: 'fashion-store-fe2d1',
    storageBucket: 'fashion-store-fe2d1.firebasestorage.app',
    iosBundleId: 'com.example.fashionStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnHLKaP02MiHCU3fsVlcUlLOjudvlRjgw',
    appId: '1:889932435607:ios:19627609cf4d74925b59d2',
    messagingSenderId: '889932435607',
    projectId: 'fashion-store-fe2d1',
    storageBucket: 'fashion-store-fe2d1.firebasestorage.app',
    iosBundleId: 'com.example.fashionStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfJA6iiyABA1ZssUw0antNCZLww6L8Up0',
    appId: '1:889932435607:web:fcd415a61d7116455b59d2',
    messagingSenderId: '889932435607',
    projectId: 'fashion-store-fe2d1',
    authDomain: 'fashion-store-fe2d1.firebaseapp.com',
    storageBucket: 'fashion-store-fe2d1.firebasestorage.app',
  );
}
